### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by winston0410** [dutiyesh/chrome-extension-cli#13]
I have long gone from Webpack, and it will be perfect if a typescript config is provided for someone who don't want to do the configuration.

**Comment by anisg** [comment]
to support typescript, I think it's way simpler to stay with webpack: it will just require some small changes in the webpack.config.js (e.g: use `ts-loader`)

**Comment by DenisTimofijuk** [comment]
Could you please at least give us an example here how to make it work? Since for me this is always a hudge hassle to setup the environment properly with bunch a different plugins. For now I was not able to have this working with TS and I giving up and just moving towards something else instead of using your brilliant tool...

**Comment by dutiyesh** [comment]
@DenisTimofijuk Thank you for using this CLI and regarding above issue give me few days, will check it and add support of TypeScript.

**Comment by dutiyesh** [comment]
@DenisTimofijuk TypeScript support added in [v1.1.0](https://github.com/dutiyesh/chrome-extension-cli/releases/tag/v1.1.0)
